# -*- coding: utf-8 -*-
"""Python_Bus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSMMWqQ0dDpyOMIMWyX9IP9F6rn_R1AK
"""

import requests #Biblioteca utilizada pelo Python para facilitar a comunicação com a internet (WEB)

!pip3 install python-dotenv

import os
from dotenv import load_dotenv

load_dotenv("../.Meu_Token")


sessao = requests.Session()
sessao.post(f"http://api.olhovivo.sptrans.com.br/v2.1/Login/Autenticar?token=34371c3670146a71fcacf94d8611a234850e99aa60d89a98b8caea8971742a71")
#Função post: Utilizada para mandar dados para um servidor WEB, para isso utilizar a URL e o dados a serem enviados como argumento

linha = sessao.get("http://api.olhovivo.sptrans.com.br/v2.1/Linha/Buscar?termosBusca=Ramos")
linha.json()

parada = sessao.get("http://api.olhovivo.sptrans.com.br/v2.1/Parada/BuscarParadasPorLinha?codigoLinha=2508")
parada = parada.json()
parada

pos = sessao.get(
    "http://api.olhovivo.sptrans.com.br/v2.1//Posicao/Linha?codigoLinha=2508"
)
pos = pos.json()

pos

import folium #Biblioteca para constituir mapas

mapa = folium.Map(location=[-23.536318, -46.651201], zoom_start=14)
for lugar in parada:
  folium.Marker(location=[lugar["py"],lugar["px"]], popup=lugar["np"]).add_to(mapa) #Localiza pela latitude e longitude marcadas na lista e adiciona um pin pra cada parada nomeada por 'np'

for bus in pos['vs']:
  folium.Marker(location=[bus["py"], bus["px"]],
  icon=folium.Icon(color='black'),
  popup="O busão ta aqui").add_to(mapa)
mapa.save('2508.html')
mapa